### ISSUE TITLE
cog_url cannot be found.

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#38]
Currently, the cog via cog_url cannot be found. 
This is an example path of the v1_cogs:
```
https://data.deadtrees.earth/cogs/v1/data/cogs/aaeff7dc-2475-48f9-aae9-90c2fb1364ea_quebec_2021-05-28-sbl-cloutier-z1-rgb//data/cogs/aaeff7dc-2475-48f9-aae9-90c2fb1364ea_quebec_2021-05-28-sbl-cloutier-z1-rgb_cog_jpeg_ovr8_q75.tif
```
The path seems pretty weird

Also, `https://data.deadtrees.earth/cogs/v1/`
shows only an empty directory:
<img width="690" alt="image" src="https://github.com/user-attachments/assets/8865bfef-91ac-4a40-bb6d-3dc7754137c4">

Anything I missed?

**Comment by JesJehle** [comment]
Seems to be related to #36

**Comment by mmaelicke** [comment]
The path seems indeed weird. There is something configured differently on the local API deployment, compared to the live version. This should be resolvable after migration. I can't have a look here, only after my vacation.

The folder is empty because the files are not migrated to the server. We can start that after my vacation.

**Comment by mmaelicke** [comment]
no the `direct-cog` url is still using the hex representation: 
https://github.com/Deadwood-ai/deadwood-api/blob/8aec512dd535e33883541ddc45f501d1e16be13e/src/routers/thumbnail.py#L70
